[package]
name = "missing_number"
version = "0.1.0"
edition = "2021"

[dependencies]
utils ={ path = "../../utils" }
anyhow = "1.0.44"
criterion = "0.3.4"
log = "0.4.14"
env_logger = "0.10.1"

[[bench]]
name = "bench"
harness = false
